#!/usr/bin/ruby
# encoding: utf-8

require 'net/http'
require 'json'
require 'uri'
require File.expand_path('~/.config/jira.rb')
# configuration example:
# $host = jira.rn
# $user = e.kovetskiy
# $password = stupidpassword

uri = URI('http://' + $host + '/rest/api/2/search')
req = Net::HTTP::Post.new(
    uri.path,
    initheader = {'Content-Type' => 'application/json'}
)
req.basic_auth $user, $password
req.body = {
    :jql => '(assignee = currentUser() AND status = "В процессе") ' +
         'or (labels in (jwh:' + $user + ':in-work))'
}.to_json

res = Net::HTTP.start(uri.host, uri.port) do |http|
  http.request req
end

json = JSON.parse res.body
issues = json['issues']
issue = issues[0]

action = ARGV.shift || 'open'
if action == 'print'
    puts issue['key']
elsif action == 'branch'
    branchField = 'customfield_10131'
    puts issue['fields'][branchField]
elsif action == 'open'
    url = 'http://' + $host + '/browse/' + issue['key']
    system('x-www-browser', url)
end
